swagger: "2.0"
info:
  description: "Cloudify REST API"
  version: "5.0.5"
  title: "Cloudify REST API"
  termsOfService: ""
  contact:
    email: "hello@cloudify.co"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api/v3.1"
tags:
- name: "blueprints"
  description: "Blueprint operations"
schemes:
- "https"
host: "localhost"
paths:
  /blueprints:
    get:
      tags:
      - "blueprints"
      summary: "List all blueprints"
      description: ""
      operationId: "addPet"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Blueprint"
definitions:
  Blueprint:
    type: "object"
    properties:
      id:
        type: "string"
      created_at:
        type: "string"
        format: "date-time"
      created_by:
        type: "string"
      updated_at:
        type: "string"
        format: "date-time"
    xml:
      name: "Blueprint"
